spring.application.name=pdfanalyzer


# Database Configuration
spring.datasource.url=mysql://root:umMNyWKnrlzVRVSkiHYyGnMiwdNeNufA@shinkansen.proxy.rlwy.net:45616/railway

spring.datasource.username=root

spring.datasource.password=umMNyWKnrlzVRVSkiHYyGnMiwdNeNufA

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

openrouter.api.key=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
